# Simple pygame program
# Import and initialize the pygame library

import pygame
import random
import numpy as np
import sys


#LOCATION PARSER, if you're creating new games copy this entire class and the two lines directly after it
#you need to indicate the location of the file that is generated by the ROS system. This class will map that position to the 
#pixel coordinates and give you a list of the read points
# the parameters for the location parser are:  
        # file_location -> Location of the lidar_output.txt, which is generated by the makers_people_detect package in the ros workspace
        # field_width_meters -> the width of the field read by the lidar through ROS, this can be found by looking in PolyGen or by viewing it in RVIZ
        # field_height_meters -> height of the field read by the lidar through ROS
        # field_width_pixels -> resolution width of the output game 
        # field_height_pixels -> resolution height of the output game 
class LocationParser(): 
    def __init__(self, file_location, field_width_meters, field_height_meters, field_width_pixels, field_height_pixels):
        #load parameters from arguments
        self.file_location = file_location #location of lidar_output.txt generated by the ROS system

        #size of the polygon that is displayed in rviz
        self.field_width_meters = field_width_meters
        self.field_height_meters = field_height_meters

        #resolution of the game
        self.field_width_pixels = field_width_pixels
        self.field_height_pixels = field_height_pixels

    def getPositions(self): 
        #open the file in read mode
        with open(self.file_location, 'r') as f:

            #read file as string
            position_string = f.read()

            #list of positions that we will be returning 
            position_list = []

            #split the read in string by line, this gives us one string per line of text generated by the ROS system
            xy_position_lines= position_string.split('\n')

            #loop through each line of text
            for a in xy_position_lines: 

                #now we do the conversion from string to float
                #the conversion is read_value * output_unit/input_unit 
                #the ros system publishes locations in meters, based on the field size we can map it to a position with this. 
                try:
                    position = (float(a.split(',')[1]) * self.field_width_pixels/self.field_width_meters, float(a.split(',')[0]) * self.field_height_pixels/self.field_height_meters)        

                    #if we were able to parse the point, add it to the list
                    position_list.append(position)
                except IndexError: 
                    print("Failed to parse position from \'%s\'" % a)
            
            #terminal spam, can be commented out
            print(position_list)
           
            # return positions
            return position_list
            
# POSITION_FILE_LOCATION = "/home/matthew/ros_ws/src/lidar-people-detect/makers_people_detection/lidar_output.txt"
POSITION_FILE_LOCATION = "/home/matthew/Documents/ARC-Projector-Games/lidar_output.txt"
lidar_positioner = LocationParser(POSITION_FILE_LOCATION, 3, 2, 1920, 1080)

pygame.init()

# Set up the drawing window
# screen = pygame.display.set_mode([1920, 1080])

#render resolution, this will be scaled to the screen
SCREEN_WIDTH, SCREEN_HEIGHT = 1920 , 1080 

screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.FULLSCREEN | pygame.SCALED)

running = True
clock = pygame.time.Clock()

class ResponsivePoint(): 
    def __init__(self, x, y): 
        self.x = x
        self.y = y

        self.xd = x
        self.yd = y

    def draw(self, screen, distortions): 
        c = pygame.Color(255,255,255)
        # pygame.draw.line(screen,c, (self.x, 0), (self.x, SCREEN_HEIGHT), 5)
        
        #for now just take the first distortion point
        #calc distance
        force = 0
        direction_vector = [0,0]
        for a in distortions: 
            force = 1/np.sqrt((a[0] - self.x) ** 2 + (a[1] - self.y) ** 2)
            # direction_vector += np.array([(distortions_x[0] - self.x), (distortions_y[0] - self.y)]) * force 
            direction_vector[0] += (a[0] - self.x) * force
            direction_vector[1] += (a[1] - self.y) * force

        self.xd = self.x -  100*direction_vector[0]
        self.yd = self.y -  100*direction_vector[1]

        pygame.draw.circle(screen, c, (self.xd, self.yd), 5)    

class ResponsiveGrid(): 
    def __init__(self, rows, columns, draw_lines=False):
        self.rows = rows
        self.columns = columns
        self.draw_lines = draw_lines

        self.points = []

        for r in range(rows): 
            for c in range(columns):
                self.points.append(ResponsivePoint(c * (SCREEN_WIDTH / self.columns) + (SCREEN_WIDTH / self.columns) * 0.5, r * (SCREEN_HEIGHT / self.rows) + (SCREEN_HEIGHT / self.rows) * 0.5))

    def draw(self, screen, distortions): 
        for a in self.points: 
            a.draw(screen, distortions)

        if(self.draw_lines):
            for index, element in enumerate(self.points): 
                #connect line to the left dot, and the above dot 
                
                left_index = index - 1
                above_index = index - self.columns

                if(left_index > 0 and above_index > 0 and index % self.columns > 0 ): 
                    pygame.draw.line(screen, (255,255,255), (element.xd, element.yd), (self.points[left_index].xd, self.points[left_index].yd), 1)
                    pygame.draw.line(screen, (255,255,255), (element.xd, element.yd), (self.points[above_index].xd, self.points[above_index].yd), 1)
        

TOTAL_ROWS = 2 * 9 
TOTAL_COLUMNS = 2 * 16

grid = ResponsiveGrid(TOTAL_ROWS, TOTAL_COLUMNS, draw_lines=True)

screen.fill((255,255,255))

while running:


    # Did the user click the window close button?

    for event in pygame.event.get():

        if event.type == pygame.QUIT:

            running = False


    # Fill the background with white

    screen.fill((0,0,0, 1))

    positions = lidar_positioner.getPositions()
    for xy in positions: 
        pygame.draw.circle(screen, (0,0,255), xy, 10)  
    grid.draw(screen, positions)

    # Flip the display
    pygame.display.flip()

    # pygame.display.flip()
    clock.tick(120)


# Done! Time to quit.

pygame.quit()
sys.exit()
